### ISSUE TITLE
Compresing/Decompressing streams.

### ISSUE THREAD

**Issue by sirherrbatka** [glv2/cl-zstd#1]
I am not sure if implementing this is possible, but it is quite handy to simply have a stream that you can pass around and the internal logic will do compression for you.

**Comment by glv2** [comment]
I added Gray streams for compression and decompression (commit 8008a8f70928fc2078df54c48de029c574f40af4).
Could you check if it works for you?

**Comment by sirherrbatka** [comment]
Sure I can and yeah, it works nicely. Thanks!
